import type { Property } from "./types";
import { galleryFor } from "./media";

/*
  Dados de exemplo para popular as telas públicas enquanto o Supabase
  não está conectado. As fotos são placeholders (sem imagens reais).
  Substituídos por dados reais do banco nas fases de integração.
*/
/** Nome do anunciante nos anúncios de exemplo (nunca uma pessoa inventada). */
const DONO_EXEMPLO = "Proprietário (exemplo)";

/** Data AAAA-MM-DD daqui a `n` dias — as datas dos exemplos andam com o tempo
 *  (fixas, viravam passado e o card mostrava "Disponível agora"). */
function emDias(n: number): string {
  return new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
}

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: "ube-001",
    title: "Imóvel mobiliado com home office no Santa Mônica",
    description:
      "Imóvel completo, pronto para morar, com cômodo dedicado ao trabalho, internet fibra e ótima localização para quem está chegando a Uberlândia.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Santa Mônica",
    lat: -18.918,
    lng: -48.257,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 68,
    minPeriodDays: 30,
    monthlyPrice: 3200,
    utilitiesMode: "fixed",
    utilitiesEstimate: 280,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 86,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-001", 20),
    videoUrl: "https://www.youtube.com/watch?v=demo-walkthrough",
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada"],
    workFeatures: ["Escritório dedicado", "Mesa de trabalho", "Cadeira ergonômica"],
    internetTier: "home_office",
    nearbyWorkspaces: [
      { name: "Coworking Center Santa Mônica", type: "coworking", distanceM: 850 },
      { name: "Café do Bloco", type: "cafe", distanceM: 400 },
    ],
    createdAt: "2026-05-10T09:00:00Z",
    ownerName: DONO_EXEMPLO,
    parkingSpots: 1,
    condoFee: 480,
    availableFrom: emDias(11),
    furnished: true,
    petsAllowed: true,
    smokingAllowed: false,
    maxGuests: 3,
    checkinAfter: "14:00",
    checkoutBefore: "11:00",
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo", "seguro_fianca"],
    // Proximidades Google (curadas) — place_ids ilustrativos no demo; em produção
    // o proprietário escolhe lugares reais e a distância aparece ao vivo.
    googlePlaces: [
      { placeId: "ChIJ-demo-hospital-stamonica", categoria: "hospital", rotulo: "Hospital Santa Mônica" },
      { placeId: "ChIJ-demo-ufu-campus", categoria: "universidade", rotulo: "UFU — Campus Santa Mônica" },
      { placeId: "ChIJ-demo-asa-coworking", categoria: "coworking", rotulo: "ASA Coworking" },
    ],
    amenityGroups: [
      { category: "trabalho", items: ["Internet fibra 300 Mbps", "Mesa de trabalho", "Cadeira ergonômica", "Monitor extra"] },
      { category: "cozinha", items: ["Fogão", "Geladeira", "Microondas", "Utensílios completos", "Cafeteira"] },
      { category: "conforto", items: ["Ar-condicionado", "Roupa de cama e banho", "Máquina de lavar", "Smart TV"] },
      { category: "edificio", items: ["Elevador", "Portaria 24h", "Academia"] },
      { category: "seguranca", items: ["Câmeras nas áreas comuns", "Interfone"] },
    ],
    proximities: [
      { category: "saude", name: "Hospital Santa Mônica", note: "8 min de carro" },
      { category: "educacao", name: "UFU — Campus Santa Mônica", note: "12 min" },
      { category: "trabalho", name: "Coworking Center", note: "10 min a pé" },
      { category: "mercado", name: "Supermercado Bahamas", note: "5 min a pé" },
      { category: "transporte", name: "Ponto de ônibus (linhas Centro)", note: "2 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-03-01", responseRate: 98, verified: true },
  },
  {
    id: "ube-002",
    title: "Studio premium no Centro, ideal para estadia profissional",
    description:
      "Studio mobiliado no coração da cidade, próximo a hospitais e coworkings. Perfeito para profissionais de saúde em plantão ou residência.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Centro",
    lat: -18.913,
    lng: -48.275,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 38,
    minPeriodDays: 30,
    monthlyPrice: 2400,
    utilitiesMode: "fixed",
    utilitiesEstimate: 200,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 74,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-002", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha equipada", "Aceita pets"],
    workFeatures: ["Mesa de trabalho"],
    internetTier: "trabalho_remoto",
    nearbyWorkspaces: [
      { name: "Hub Central Coworking", type: "coworking", distanceM: 600 },
      { name: "Sala Reunião Empresarial", type: "meeting_room", distanceM: 900 },
    ],
    createdAt: "2026-06-01T09:00:00Z",
    ownerName: DONO_EXEMPLO,
    parkingSpots: 0,
    condoFee: 350,
    availableFrom: emDias(15),
    furnished: true,
    petsAllowed: true,
    smokingAllowed: false,
    maxGuests: 2,
    checkinAfter: "15:00",
    checkoutBefore: "11:00",
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "titulo", "seguro_fianca"],
    amenityGroups: [
      { category: "trabalho", items: ["Internet fibra 200 Mbps", "Mesa de trabalho"] },
      { category: "cozinha", items: ["Cooktop", "Geladeira", "Microondas", "Utensílios básicos"] },
      { category: "conforto", items: ["Ar-condicionado", "Roupa de cama e banho", "Smart TV"] },
      { category: "edificio", items: ["Elevador", "Portaria 24h"] },
      { category: "seguranca", items: ["Câmeras nas áreas comuns"] },
    ],
    proximities: [
      { category: "saude", name: "Hospital e Maternidade Municipal", note: "6 min a pé" },
      { category: "trabalho", name: "Hub Central Coworking", note: "6 min a pé" },
      { category: "mercado", name: "Mercado do Centro", note: "3 min a pé" },
      { category: "transporte", name: "Terminal Central", note: "7 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-06-15", responseRate: 92, verified: true },
  },
  {
    id: "ube-003",
    title: "Casa 3 quartos para famílias em transição",
    description:
      "Casa espaçosa e mobiliada, garagem e quintal. Ideal para famílias em mudança, reforma ou espera pelo imóvel próprio.",
    propertyType: "Casa",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Tibery",
    lat: -18.89,
    lng: -48.24,
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 120,
    minPeriodDays: 60,
    monthlyPrice: 4100,
    utilitiesMode: "real",
    utilitiesEstimate: 0,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: false,
    acceptsInsurance: false,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: false,
    readyToLiveScore: 52,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "subleased",
    subleaseAuthorized: true,
    photos: galleryFor("ube-003", 8),
    amenities: ["Mobiliado completo", "Máquina de lavar", "Cozinha equipada", "Aceita pets"],
    workFeatures: [],
    internetTier: "trabalho_remoto",
    nearbyWorkspaces: [{ name: "Coworking Tibery", type: "coworking", distanceM: 1800 }],
    createdAt: "2026-06-15T09:00:00Z",
    ownerName: DONO_EXEMPLO,
    // Anúncio propositalmente "enxuto": sem amenityGroups/proximities/reviews/owner —
    // demonstra que as seções somem com elegância quando o dado não foi preenchido.
    parkingSpots: 2,
    furnished: true,
    availableFrom: emDias(19),
    maxGuests: 5,
    faixasAceitas: ["media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada"],
  },
  {
    id: "ube-004",
    title: "Studio ao lado do Hospital de Clínicas (UFU)",
    description:
      "Studio mobiliado a poucos minutos do Hospital de Clínicas. Ideal para acompanhantes de pacientes, profissionais de saúde em plantão ou residência. Tudo pronto para morar já no primeiro dia.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Umuarama",
    lat: -18.919,
    lng: -48.29,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 32,
    minPeriodDays: 30,
    monthlyPrice: 2300,
    utilitiesMode: "fixed",
    utilitiesEstimate: 210,
    utilitiesOverageMargin: 20,
    prepFee: 350,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 180,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 80,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-004", 10),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha compacta equipada", "Smart TV"],
    workFeatures: ["Internet fibra", "Bancada de trabalho"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Biblioteca UFU Umuarama", type: "cafe", distanceM: 600 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-02T09:00:00Z",
    parkingSpots: 1,
    condoFee: 320,
    furnished: true,
    petsAllowed: false,
    maxGuests: 2,
    availableFrom: emDias(23),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    proximities: [
      { category: "saude", name: "Hospital de Clínicas — UFU", note: "4 min de carro" },
      { category: "educacao", name: "UFU — Campus Umuarama", note: "6 min a pé" },
      { category: "mercado", name: "Supermercado", note: "3 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-08-01", responseRate: 95, verified: true },
  },
  {
    id: "ube-005",
    title: "Imóvel mobiliado de 2 quartos para pacientes e acompanhantes",
    description:
      "Imóvel silencioso e acessível, pensado para famílias que acompanham um tratamento prolongado em Uberlândia. Próximo aos principais hospitais, com estrutura completa para estadias de semanas a meses.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Aparecida",
    lat: -18.915,
    lng: -48.273,
    bedrooms: 2,
    bathrooms: 1,
    areaM2: 58,
    minPeriodDays: 30,
    monthlyPrice: 2850,
    utilitiesMode: "fixed",
    utilitiesEstimate: 240,
    utilitiesOverageMargin: 20,
    prepFee: 400,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 220,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 84,
    tagHomeOffice: false,
    tagWorkLocated: false,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-005", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada", "Acessível"],
    workFeatures: ["Internet fibra"],
    internetTier: "basica",
    nearbyWorkspaces: [{ name: "Praça Sérgio Pacheco", type: "cafe", distanceM: 500 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-05-28T09:00:00Z",
    parkingSpots: 1,
    condoFee: 380,
    furnished: true,
    petsAllowed: true,
    maxGuests: 4,
    availableFrom: emDias(27),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    proximities: [
      { category: "saude", name: "Hospital do Câncer de Uberlândia", note: "7 min de carro" },
      { category: "saude", name: "UMC — Uberlândia Medical Center", note: "9 min de carro" },
      { category: "mercado", name: "Farmácia 24h", note: "2 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-05-01", responseRate: 99, verified: true },
  },
  {
    id: "ube-006",
    title: "Imóvel executivo mobiliado no Centro",
    description:
      "Imóvel de alto padrão para executivos em transferência ou projeto corporativo. Localização central, home office equipado e tudo pronto para trabalhar no primeiro dia.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Centro",
    lat: -18.918,
    lng: -48.277,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 72,
    minPeriodDays: 30,
    monthlyPrice: 3600,
    utilitiesMode: "fixed",
    utilitiesEstimate: 300,
    utilitiesOverageMargin: 20,
    prepFee: 480,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 260,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 90,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-006", 14),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada", "Smart TV"],
    workFeatures: ["Escritório dedicado", "Internet fibra 300 Mbps", "Cadeira ergonômica", "Monitor extra"],
    internetTier: "home_office",
    nearbyWorkspaces: [
      { name: "ASA Coworking", type: "coworking", distanceM: 700 },
      { name: "Café Central", type: "cafe", distanceM: 250 },
    ],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-10T09:00:00Z",
    parkingSpots: 1,
    condoFee: 520,
    furnished: true,
    petsAllowed: false,
    maxGuests: 3,
    availableFrom: emDias(31),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo", "seguro_fianca"],
    proximities: [
      { category: "trabalho", name: "Centro empresarial", note: "5 min a pé" },
      { category: "transporte", name: "Terminal Central", note: "6 min a pé" },
      { category: "mercado", name: "Supermercado", note: "4 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-02-01", responseRate: 97, verified: true },
  },
  {
    id: "ube-007",
    title: "Studio para profissional em projeto — bairro Brasil",
    description:
      "Studio moderno e funcional para quem chega a Uberlândia para um projeto de alguns meses. Enxuto, bem localizado e com internet de trabalho.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Brasil",
    lat: -18.912,
    lng: -48.266,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 40,
    minPeriodDays: 30,
    monthlyPrice: 2500,
    utilitiesMode: "fixed",
    utilitiesEstimate: 220,
    utilitiesOverageMargin: 20,
    prepFee: 360,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 190,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 82,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-007", 10),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha compacta", "Smart TV"],
    workFeatures: ["Internet fibra", "Mesa de trabalho"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Coworking Brasil", type: "coworking", distanceM: 900 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-18T09:00:00Z",
    parkingSpots: 1,
    condoFee: 300,
    furnished: true,
    petsAllowed: false,
    maxGuests: 2,
    availableFrom: emDias(35),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-09-01", responseRate: 94, verified: true },
  },
  {
    id: "ube-008",
    title: "Casa 3 quartos para família em transição — Jardim Karaíba",
    description:
      "Casa espaçosa e mobiliada em bairro nobre, ideal para famílias em mudança, reforma do imóvel próprio ou transição de carreira. Quintal, churrasqueira e muito espaço.",
    propertyType: "Casa",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Jardim Karaíba",
    lat: -18.95,
    lng: -48.284,
    bedrooms: 3,
    bathrooms: 3,
    areaM2: 150,
    minPeriodDays: 60,
    monthlyPrice: 5200,
    utilitiesMode: "fixed",
    utilitiesEstimate: 420,
    utilitiesOverageMargin: 20,
    prepFee: 650,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 380,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 88,
    tagHomeOffice: true,
    tagWorkLocated: false,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-008", 16),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada", "Quintal", "Churrasqueira"],
    workFeatures: ["Escritório dedicado", "Internet fibra"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Shopping Jardim Karaíba", type: "cafe", distanceM: 1200 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-05-20T09:00:00Z",
    parkingSpots: 2,
    condoFee: 0,
    furnished: true,
    petsAllowed: true,
    childrenAllowed: true,
    maxGuests: 6,
    availableFrom: emDias(39),
    faixasAceitas: ["media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo"],
    proximities: [
      { category: "educacao", name: "Escola particular", note: "8 min de carro" },
      { category: "mercado", name: "Shopping e supermercado", note: "6 min de carro" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-04-01", responseRate: 96, verified: true },
  },
  {
    id: "ube-009",
    title: "Imóvel mobiliado para pós-graduação e pesquisadores — Santa Mônica",
    description:
      "Imóvel compacto e tranquilo ao lado do campus Santa Mônica da UFU. Perfeito para pós-graduandos, professores visitantes e pesquisadores em estadia temporária.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Santa Mônica",
    lat: -18.921,
    lng: -48.259,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 36,
    minPeriodDays: 30,
    monthlyPrice: 2100,
    utilitiesMode: "fixed",
    utilitiesEstimate: 190,
    utilitiesOverageMargin: 20,
    prepFee: 330,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 170,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 83,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-009", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha compacta", "Smart TV"],
    workFeatures: ["Internet fibra", "Mesa de estudos"],
    internetTier: "home_office",
    nearbyWorkspaces: [
      { name: "Biblioteca Central UFU", type: "cafe", distanceM: 450 },
      { name: "Coworking Santa Mônica", type: "coworking", distanceM: 800 },
    ],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-25T09:00:00Z",
    parkingSpots: 1,
    condoFee: 290,
    furnished: true,
    petsAllowed: false,
    maxGuests: 2,
    availableFrom: emDias(43),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    proximities: [
      { category: "educacao", name: "UFU — Campus Santa Mônica", note: "6 min a pé" },
      { category: "mercado", name: "Supermercado Bahamas", note: "4 min a pé" },
    ],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-07-01", responseRate: 98, verified: true },
  },
  {
    id: "ube-010",
    title: "Imóvel de 2 quartos mobiliado no Tibery",
    description:
      "Imóvel confortável e bem localizado, ideal para quem chega a Uberlândia por alguns meses. Mobiliado e pronto para morar.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Tibery",
    lat: -18.903,
    lng: -48.251,
    bedrooms: 2,
    bathrooms: 1,
    areaM2: 65,
    minPeriodDays: 30,
    monthlyPrice: 3000,
    utilitiesMode: "fixed",
    utilitiesEstimate: 250,
    utilitiesOverageMargin: 20,
    prepFee: 400,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 220,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 81,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-010", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada"],
    workFeatures: ["Internet fibra"],
    internetTier: "trabalho_remoto",
    nearbyWorkspaces: [{ name: "Coworking Tibery", type: "coworking", distanceM: 1000 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-30T09:00:00Z",
    parkingSpots: 1,
    condoFee: 360,
    furnished: true,
    petsAllowed: true,
    maxGuests: 4,
    availableFrom: emDias(47),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-06-01", responseRate: 93, verified: true },
  },
  {
    id: "ube-011",
    title: "Studio próximo à UFU — Osvaldo Rezende",
    description:
      "Studio prático para estudantes de pós, pesquisadores ou jovens profissionais, a poucos minutos do campus e do centro.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Osvaldo Rezende",
    lat: -18.913,
    lng: -48.283,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 34,
    minPeriodDays: 30,
    monthlyPrice: 2200,
    utilitiesMode: "fixed",
    utilitiesEstimate: 200,
    utilitiesOverageMargin: 20,
    prepFee: 330,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 170,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 79,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-011", 10),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha compacta", "Smart TV"],
    workFeatures: ["Internet fibra", "Mesa de estudos"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Biblioteca UFU", type: "cafe", distanceM: 700 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-07-02T09:00:00Z",
    parkingSpots: 0,
    condoFee: 270,
    furnished: true,
    petsAllowed: false,
    maxGuests: 2,
    availableFrom: emDias(51),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-10-01", responseRate: 91, verified: true },
  },
  {
    id: "ube-012",
    title: "Imóvel mobiliado de 1 quarto para profissional — Saraiva",
    description:
      "Imóvel de 1 quarto, moderno e silencioso, ideal para um profissional em projeto de média duração na cidade.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Saraiva",
    lat: -18.925,
    lng: -48.283,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 45,
    minPeriodDays: 30,
    monthlyPrice: 2700,
    utilitiesMode: "fixed",
    utilitiesEstimate: 230,
    utilitiesOverageMargin: 20,
    prepFee: 370,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 200,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 83,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-012", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada"],
    workFeatures: ["Escritório dedicado", "Internet fibra 300 Mbps"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Café Saraiva", type: "cafe", distanceM: 350 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-07-05T09:00:00Z",
    parkingSpots: 1,
    condoFee: 390,
    furnished: true,
    petsAllowed: false,
    maxGuests: 2,
    availableFrom: emDias(55),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-03-15", responseRate: 96, verified: true },
  },
  {
    id: "ube-013",
    title: "Casa 2 quartos com quintal — Morada da Colina",
    description:
      "Casa aconchegante com quintal, ideal para famílias pequenas em transição ou profissionais que preferem mais espaço e sossego.",
    propertyType: "Casa",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Morada da Colina",
    lat: -18.933,
    lng: -48.29,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 100,
    minPeriodDays: 60,
    monthlyPrice: 4200,
    utilitiesMode: "fixed",
    utilitiesEstimate: 340,
    utilitiesOverageMargin: 20,
    prepFee: 550,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 320,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 85,
    tagHomeOffice: true,
    tagWorkLocated: false,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-013", 14),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada", "Quintal"],
    workFeatures: ["Escritório dedicado", "Internet fibra"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Center Shopping", type: "cafe", distanceM: 1500 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-22T09:00:00Z",
    parkingSpots: 2,
    condoFee: 0,
    furnished: true,
    petsAllowed: true,
    childrenAllowed: true,
    maxGuests: 4,
    availableFrom: emDias(59),
    faixasAceitas: ["media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-05-20", responseRate: 94, verified: true },
  },
  {
    id: "ube-014",
    title: "Imóvel mobiliado de 3 quartos premium — Cidade Jardim",
    description:
      "Imóvel amplo e sofisticado em bairro nobre, para executivos com família ou estadias de alto padrão. Lazer completo no condomínio.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Cidade Jardim",
    lat: -18.94,
    lng: -48.278,
    bedrooms: 3,
    bathrooms: 3,
    areaM2: 110,
    minPeriodDays: 30,
    monthlyPrice: 5500,
    utilitiesMode: "fixed",
    utilitiesEstimate: 400,
    utilitiesOverageMargin: 20,
    prepFee: 620,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 360,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 92,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-014", 16),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada", "Smart TV", "Varanda gourmet"],
    workFeatures: ["Escritório dedicado", "Internet fibra 500 Mbps", "Cadeira ergonômica"],
    internetTier: "home_office",
    nearbyWorkspaces: [{ name: "Business Center Cidade Jardim", type: "coworking", distanceM: 800 }],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-06-15T09:00:00Z",
    parkingSpots: 2,
    condoFee: 780,
    furnished: true,
    petsAllowed: false,
    maxGuests: 5,
    availableFrom: emDias(63),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-01-10", responseRate: 97, verified: true },
  },
  {
    id: "ube-015",
    title: "Studio compacto no Fundinho — centro histórico",
    description:
      "Studio charmoso no bairro mais boêmio da cidade, para jovens profissionais e trabalho remoto. Perto de cafés, bares e coworkings.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Fundinho",
    lat: -18.916,
    lng: -48.279,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 30,
    minPeriodDays: 30,
    monthlyPrice: 2000,
    utilitiesMode: "fixed",
    utilitiesEstimate: 180,
    utilitiesOverageMargin: 20,
    prepFee: 320,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 160,
    issuesInvoice: false,
    acceptsInsurance: true,
    rating: 0,
    reviewCount: 0,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 80,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-015", 10),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha compacta", "Smart TV"],
    workFeatures: ["Internet fibra", "Mesa de trabalho"],
    internetTier: "home_office",
    nearbyWorkspaces: [
      { name: "Coworking Fundinho", type: "coworking", distanceM: 300 },
      { name: "Café do Largo", type: "cafe", distanceM: 150 },
    ],
    ownerName: DONO_EXEMPLO,
    createdAt: "2026-07-08T09:00:00Z",
    parkingSpots: 0,
    condoFee: 250,
    furnished: true,
    petsAllowed: true,
    maxGuests: 2,
    availableFrom: emDias(67),
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "seguro_fianca"],
    owner: { name: DONO_EXEMPLO, memberSince: "2025-11-01", responseRate: 92, verified: true },
  },
];

export function getPropertyById(id: string): Property | undefined {
  return SAMPLE_PROPERTIES.find((p) => p.id === id);
}

export function getPropertiesByCity(city: string): Property[] {
  const target = city.toLowerCase();
  return SAMPLE_PROPERTIES.filter((p) => p.city.toLowerCase() === target);
}
