import type { Property } from "./types";
import { galleryFor } from "./media";

/*
  Dados de exemplo para popular as telas públicas enquanto o Supabase
  não está conectado. As fotos são placeholders (sem imagens reais).
  Substituídos por dados reais do banco nas fases de integração.
*/
export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: "ube-001",
    title: "Apartamento mobiliado com home office no Santa Mônica",
    description:
      "Apartamento completo, pronto para morar, com cômodo dedicado ao trabalho, internet fibra e ótima localização para quem está chegando a Uberlândia.",
    propertyType: "Apartamento",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Santa Mônica",
    lat: -18.918,
    lng: -48.257,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 68,
    minPeriodDays: 30,
    monthlyPrice: 3200,
    utilitiesMode: "fixed",
    utilitiesEstimate: 280,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: true,
    acceptsInsurance: true,
    rating: 4.8,
    reviewCount: 12,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 86,
    tagHomeOffice: true,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-001", 20),
    videoUrl: "https://www.youtube.com/watch?v=demo-walkthrough",
    amenities: ["Mobiliado completo", "Ar-condicionado", "Máquina de lavar", "Cozinha equipada"],
    workFeatures: ["Escritório dedicado", "Mesa de trabalho", "Cadeira ergonômica"],
    internetTier: "home_office",
    nearbyWorkspaces: [
      { name: "Coworking Center Santa Mônica", type: "coworking", distanceM: 850 },
      { name: "Café do Bloco", type: "cafe", distanceM: 400 },
    ],
    createdAt: "2026-05-10T09:00:00Z",
    ownerName: "Marcos A.",
    parkingSpots: 1,
    condoFee: 480,
    availableFrom: "2026-07-01",
    furnished: true,
    petsAllowed: true,
    smokingAllowed: false,
    maxGuests: 3,
    checkinAfter: "14:00",
    checkoutBefore: "11:00",
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada", "titulo", "seguro_fianca"],
    // Proximidades Google (curadas) — place_ids ilustrativos no demo; em produção
    // o proprietário escolhe lugares reais e a distância aparece ao vivo.
    googlePlaces: [
      { placeId: "ChIJ-demo-hospital-stamonica", categoria: "hospital", rotulo: "Hospital Santa Mônica" },
      { placeId: "ChIJ-demo-ufu-campus", categoria: "universidade", rotulo: "UFU — Campus Santa Mônica" },
      { placeId: "ChIJ-demo-asa-coworking", categoria: "coworking", rotulo: "ASA Coworking" },
    ],
    amenityGroups: [
      { category: "trabalho", items: ["Internet fibra 300 Mbps", "Mesa de trabalho", "Cadeira ergonômica", "Monitor extra"] },
      { category: "cozinha", items: ["Fogão", "Geladeira", "Microondas", "Utensílios completos", "Cafeteira"] },
      { category: "conforto", items: ["Ar-condicionado", "Roupa de cama e banho", "Máquina de lavar", "Smart TV"] },
      { category: "edificio", items: ["Elevador", "Portaria 24h", "Academia"] },
      { category: "seguranca", items: ["Câmeras nas áreas comuns", "Interfone"] },
    ],
    proximities: [
      { category: "saude", name: "Hospital Santa Mônica", note: "8 min de carro" },
      { category: "educacao", name: "UFU — Campus Santa Mônica", note: "12 min" },
      { category: "trabalho", name: "Coworking Center", note: "10 min a pé" },
      { category: "mercado", name: "Supermercado Bahamas", note: "5 min a pé" },
      { category: "transporte", name: "Ponto de ônibus (linhas Centro)", note: "2 min a pé" },
    ],
    reviews: [
      { author: "Carlos", rating: 5, comment: "Imóvel impecável e proprietário atencioso. Contrato e nota fiscal sem dor de cabeça.", date: "2026-04-18" },
      { author: "Fernanda", rating: 4.5, comment: "Ótimo para trabalhar de casa. Internet excelente e tudo mobiliado como anunciado.", date: "2026-03-02" },
    ],
    owner: { name: "Marcos A.", memberSince: "2025-03-01", responseRate: 98, verified: true },
  },
  {
    id: "ube-002",
    title: "Studio premium no Centro, ideal para estadia profissional",
    description:
      "Studio mobiliado no coração da cidade, próximo a hospitais e coworkings. Perfeito para profissionais de saúde em plantão ou residência.",
    propertyType: "Studio",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Centro",
    lat: -18.913,
    lng: -48.275,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 38,
    minPeriodDays: 30,
    monthlyPrice: 2400,
    utilitiesMode: "fixed",
    utilitiesEstimate: 200,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: true,
    acceptsInsurance: true,
    rating: 4.6,
    reviewCount: 8,
    status: "active",
    readyToLiveBadge: true,
    readyToLiveScore: 74,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "own",
    photos: galleryFor("ube-002", 12),
    amenities: ["Mobiliado completo", "Ar-condicionado", "Cozinha equipada", "Aceita pets"],
    workFeatures: ["Mesa de trabalho"],
    internetTier: "trabalho_remoto",
    nearbyWorkspaces: [
      { name: "Hub Central Coworking", type: "coworking", distanceM: 600 },
      { name: "Sala Reunião Empresarial", type: "meeting_room", distanceM: 900 },
    ],
    createdAt: "2026-06-01T09:00:00Z",
    ownerName: "Patrícia L.",
    parkingSpots: 0,
    condoFee: 350,
    availableFrom: "2026-08-01",
    furnished: true,
    petsAllowed: true,
    smokingAllowed: false,
    maxGuests: 2,
    checkinAfter: "15:00",
    checkoutBefore: "11:00",
    faixasAceitas: ["temporada", "media_estadia"],
    garantiasAceitas: ["caucao_avista", "titulo", "seguro_fianca"],
    amenityGroups: [
      { category: "trabalho", items: ["Internet fibra 200 Mbps", "Mesa de trabalho"] },
      { category: "cozinha", items: ["Cooktop", "Geladeira", "Microondas", "Utensílios básicos"] },
      { category: "conforto", items: ["Ar-condicionado", "Roupa de cama e banho", "Smart TV"] },
      { category: "edificio", items: ["Elevador", "Portaria 24h"] },
      { category: "seguranca", items: ["Câmeras nas áreas comuns"] },
    ],
    proximities: [
      { category: "saude", name: "Hospital e Maternidade Municipal", note: "6 min a pé" },
      { category: "trabalho", name: "Hub Central Coworking", note: "6 min a pé" },
      { category: "mercado", name: "Mercado do Centro", note: "3 min a pé" },
      { category: "transporte", name: "Terminal Central", note: "7 min a pé" },
    ],
    reviews: [
      { author: "Rafael", rating: 5, comment: "Perfeito para quem trabalha no Centro. Tudo a pé.", date: "2026-05-20" },
    ],
    owner: { name: "Patrícia L.", memberSince: "2025-06-15", responseRate: 92, verified: true },
  },
  {
    id: "ube-003",
    title: "Casa 3 quartos para famílias em transição",
    description:
      "Casa espaçosa e mobiliada, garagem e quintal. Ideal para famílias em mudança, reforma ou espera pelo imóvel próprio.",
    propertyType: "Casa",
    city: "Uberlândia",
    state: "MG",
    neighborhood: "Tibery",
    lat: -18.89,
    lng: -48.24,
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 120,
    minPeriodDays: 60,
    monthlyPrice: 4100,
    utilitiesMode: "real",
    utilitiesEstimate: 0,
    utilitiesOverageMargin: 20,
    prepFee: 450,
    checkoutCleaningEnabled: true,
    checkoutCleaningFee: 250,
    issuesInvoice: false,
    acceptsInsurance: false,
    rating: 4.2,
    reviewCount: 3,
    status: "active",
    readyToLiveBadge: false,
    readyToLiveScore: 52,
    tagHomeOffice: false,
    tagWorkLocated: true,
    tagCondoApproved: true,
    ownershipType: "subleased",
    subleaseAuthorized: true,
    photos: galleryFor("ube-003", 8),
    amenities: ["Mobiliado completo", "Máquina de lavar", "Cozinha equipada", "Aceita pets"],
    workFeatures: [],
    internetTier: "trabalho_remoto",
    nearbyWorkspaces: [{ name: "Coworking Tibery", type: "coworking", distanceM: 1800 }],
    createdAt: "2026-06-15T09:00:00Z",
    ownerName: "Família Souza (gestão)",
    // Anúncio propositalmente "enxuto": sem amenityGroups/proximities/reviews/owner —
    // demonstra que as seções somem com elegância quando o dado não foi preenchido.
    parkingSpots: 2,
    furnished: true,
    availableFrom: "2026-09-01",
    maxGuests: 5,
    faixasAceitas: ["media_estadia", "longa"],
    garantiasAceitas: ["caucao_avista", "caucao_parcelada"],
  },
];

export function getPropertyById(id: string): Property | undefined {
  return SAMPLE_PROPERTIES.find((p) => p.id === id);
}

export function getPropertiesByCity(city: string): Property[] {
  const target = city.toLowerCase();
  return SAMPLE_PROPERTIES.filter((p) => p.city.toLowerCase() === target);
}
